### ISSUE TITLE
Question about attention

### ISSUE THREAD

**Issue by JaniceXiong** [ShuyangCao/hibrids_summ#1]
Hi, thanks for your outstanding work!
I wonder how to process long documents like 5120 or 16384 tokens written on paper. Do you use sparse attention? 
I saw that you adjust the attention using learnable hierarchical bias and only keep salient bias. But I did not figure out whether the token in the input sequence still attends to every token? For input token i, is j still range from 1-5120?

**Comment by ShuyangCao** [comment]
Good question! 
- We use Longformer, which adopts sparse attention with a window size of 1024 (https://huggingface.co/allenai/led-large-16384).
- For the hierarchical bias, we only use it on the sparse attention.
- Longformer suggests using global attention only on the first token. We also try using global attention on section special tokens so that these section special tokens can fully leverage the hierarchical bias. However, it turns out that using global tokens on tokens other than the first token would result in model degeneration.

**Comment by JaniceXiong** [comment]
> * For the hierarchical bias, we only use it on the sparse attention.
> * Longformer suggests using global attention only on the first token. We also try using global attention on section special tokens so that these section special tokens can fully leverage the hierarchical bias. However, it turns out that using global tokens on tokens other than the first token would result in model degeneration.

Thanks for your kindly reply :)

- so the token i only attend to other token j in the sliding window and the attention is adjusted by hierarchical bias
- What are the section special tokens as you said? Can you give me an example?

**Comment by ShuyangCao** [comment]
- Yes
- In the paper, we mention that we add special tokens such as `[Sec-Lv1]` to indicate the start of a section and its hierarchical level. In implementation, `[Sec-lv1]` is mapped to an unused (or rarely used) BPE token. For example, the 49613-th token in the vocabulary`Ã£Ä¥Â¼Ã£Ä¥Â`.

**Comment by JaniceXiong** [comment]
> * Yes
> * In the paper, we mention that we add special tokens such as `[Sec-Lv1]` to indicate the start of a section and its hierarchical level. In implementation, `[Sec-lv1]` is mapped to an unused (or rarely used) BPE token. For example, the 49613-th token in the vocabulary`Ã£Ä¥Â¼Ã£Ä¥Â`.

Thanks! I understood these details :)
By the way, is the code in models/level_section_tokens an implementation of SECTOK or SECBIAS in the paper?

**Comment by ShuyangCao** [comment]
It is the code for LVLSECTOK

**Comment by JaniceXiong** [comment]
Another question is that B is a lookup table corresponding to PathLen and LvlDiff, could you tell me what is the dimension of B and where did you define B (because B is a trainable parameter) in the source code? Thanks! @ShuyangCao
